import SwiftUI

// generated by https://rootloops.sh?sugar=7&colors=2&sogginess=4&flavor=1&fruit=10&milk=1
enum Theme {
    static let background = Color(hex: 0x261D35)
    static let foreground = Color(hex: 0xEDE9F5)
    static let pillHeight: CGFloat = 20
    static let font = Font.system(size: 13)
}

struct BarView: View {
    var body: some View {
        HStack(spacing: 4) {
            AeroSpaceView()
            Spacer(minLength: 0)
            HStack(spacing: 4) {
                StatusItemsView()
                SpotifyView()
                ClockView()
            }
        }
        .padding(.horizontal, 10)
        .padding(.top, 6)
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)
        .font(Theme.font)
        .foregroundStyle(Theme.foreground)
    }
}

/// The capsule every bar item sits in.
struct Pill<Content: View>: View {
    var padding: CGFloat = 16
    /// Tints the capsule, e.g. while hovered.
    var highlighted = false
    @ViewBuilder var content: Content

    var body: some View {
        HStack(spacing: 0) { content }
            .padding(.horizontal, padding)
            .frame(height: Theme.pillHeight)
            .background {
                Capsule()
                    .fill(Theme.background)
                    .overlay(Capsule().fill(Theme.foreground.opacity(highlighted ? 0.12 : 0)))
            }
            .lineLimit(1)
    }
}

extension View {
    /// Call `action` with this view's frame in its window (SwiftUI's
    /// top-left space) now and whenever it changes.
    func onWindowFrameChange(_ action: @escaping (CGRect) -> Void) -> some View {
        background(GeometryReader { geo in
            Color.clear
                .onAppear { action(geo.frame(in: .global)) }
                .onChange(of: geo.frame(in: .global)) { _, frame in action(frame) }
        })
    }
}

extension Color {
    init(hex: UInt32) {
        self.init(
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255)
    }
}
