name: Build macOS App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build app bundle
        run: make bundle

      - name: Zip app bundle
        run: ditto -c -k --keepParent .build/doubar.app doubar-macos.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: doubar-macos
          path: doubar-macos.zip
